### ISSUE TITLE
Not compatible with Guzzle 7.X

### ISSUE THREAD

**Issue by codeandvisual** [biscolab/google-maps-php-sdk#13]
We're using this package in a Laravel 7 project that we're upgrading to Laravel 8. Laravel 8 requires guzzlehttp/guzzle ^7.0.1 however this package currently only supports guzzle 5 & 6 in it's composer.json

`Problem 1
    - biscolab/google-maps-php-sdk[0.8.0, ..., 0.8.2] require guzzlehttp/guzzle 5.*|6.* -> found guzzlehttp/guzzle[5.0.0, ..., 5.3.x-dev, 6.0.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).
    - Root composer.json requires biscolab/google-maps-php-sdk ^0.8 -> satisfiable by biscolab/google-maps-php-sdk[0.8.0, 0.8.2].`

**Comment by pioneersingh321** [comment]
how can we use Guzzle 7.X in this ?

**Comment by biscolab** [comment]
Fixed v0.9.0 [35ac50]
