### ISSUE TITLE
Language GoogleMapsApiConfigFields Geocoding

### ISSUE THREAD

**Issue by asadowski10** [biscolab/google-maps-php-sdk#8]
Hi there,

I use your very useful and easy to use SDK. Thank you for this open source work!

Would it be possible to update it by adding the language parameter (Optional parameters in a Geocoding request).
My client is French and wants to display the countries in French. 
Currently, I maintain an English > French translation in my code which could be corrected by the language parameter passed in the request.

Thanks a lot

**Comment by biscolab** [comment]
@asadowski10, please update the package and go to https://gmaps-php-docs.biscolab.com/docs/geocoding. I added `setLanguage` method to Geocoding service

**Comment by asadowski10** [comment]
Thanks a lot for your reactivity ! 
Best,
